### PR TITLE
usma92 training, test and validation

### PR DESCRIPTION
**Pull request by usma92**

### CODE REVIEW

**Review by cegme — CHANGES_REQUESTED** [review]
Hey @usma92, it looks like you added quotes around the last column. Please remove. There should be no diff changes in the existing code.

**Comment by cegme** [comment]
Note that there is an update. Be sure to grab the latest before submitting the next pull request.

**Comment by cegme** [comment]
@usma92 I want to make sure you know that you didn't have to close it. Also, your changes were not yet merged. You should be able to fetch from upstream and easily make the changes.

**Comment by usma92** [comment]
I went ahead and simply reforked, updated changes and resubmitted.

**Pull request closed without merging**
