### PR TITLE
Added Tashfeen's 90 records (50 training + 30 validation + 10 test)

### PR DESCRIPTION
**Pull request by simurgh9**
Hope everything looks okay.

### CODE REVIEW

**Review by cegme — CHANGES_REQUESTED** [review]
File format looks fine. Consider adding more context to the word entries so, they are more identifiable. 
Someone submitted before you. Please re-request a review

**Comment by simurgh9** [comment]
By context do you mean make the lines a bit longer?

And okay.

**Comment by cegme** [comment]
> By context do you mean make the lines a bit longer?
Yea, it will help with the prediction. But, I will still accept your submission if you rather not make it longer.

**Comment by simurgh9** [comment]
> I will still accept your submission if you rather not make it longer.

Than I'll just re-request a review for now since I am chasing the clock a little bit. If I got more time towards the tail-end of this project, I'll make the lines bigger. Thanks Dr. Grant!

**Comment by simurgh9** [comment]
Okay I have synced my fork. Could you merge this now?

**Review by cegme — APPROVED** [review]
:shipit:

**Pull request merged**
