### PR TITLE
Update unredactor.tsv

### PR DESCRIPTION
**Pull request by daedalus404**
Zackery Herman added 90 entries

### CODE REVIEW

**Review by cegme — CHANGES_REQUESTED** [review]
Some entries are longer than 1024, but that's okay. Please resolve the conflicts and rerequest a pull request

**Review by daedalus404 — COMMENTED** [review]
Everything looks fine from my end. I'm not sure why it says there is a merge conflict when the only thing changing are additions to the end of the previous commit.

**Comment by cegme** [comment]
Pull the latest from upstream. The command-line link could help

**Comment by daedalus404** [comment]
Okay, have the conflicts resolved!

**Review by cegme — CHANGES_REQUESTED** [review]
Something strange is happening. I suggest closing this pr and reopening. Try and keep just your changes.
image

**Pull request closed without merging**
