### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by ramrao0102**
Want to contribute to the .tsv file.

### CODE REVIEW

**Review by cegme — CHANGES_REQUESTED** [review]
Close, please merge/append your new rows into unredactor.csv. There should be one merged file, no added files.

**Comment by ramrao0102** [comment]
After several attempts of trying to answer the Q, I may have provided what you need?

**Comment by cegme** [comment]
Make sure there’s only one reduction for each line. Also ensure if you have <br/> symbols in the context that either were in the original file.

**Comment by ramrao0102** [comment]
so even if we have the same word appear twice in a sentence, we only get to redact it once?  There are no symbols in the context. the <br> you see is in the text.  The context has a string with either one word or two, first_name and last_name with a space in between.  Is that ok?

**Comment by ramrao0102** [comment]
I checked again, there is only one context word.

**Comment by ramrao0102** [comment]
I took out the special characters.  Hopefully, this worked.  When I look on the file, it seems to show differences from what I posted earlier this afternoon.  I am a github and pull request newbie....

**Comment by cegme** [comment]
Here 'Work' is listed as a name:

```
RamRao training Work Just a handful of films have nibbled round the caps, including Performance, ████ I
```

This entry has multiple redactions. 

```
Sadako This sees a lot of the scenes shot inside a theatre, which provides a suitably eerie backdrop for ██████ doomed quest to lead a normal life and battle the demons of her past that lurk ever closer With regards to filling in the blanks left open in Ring and Ring 2, this film does very little, for we are already aware that ██████ was pushed to the bottom of the well by her step father, and only hints at the source of the true evil lurking inside her, without giving a clue of its origin or past
``` 

Please fix. Also, I will need to add a few more pull requests so fetch the latest before the next request

**Comment by ramrao0102** [comment]
.<br /<br> it did not see the . as the end of line.  and I just replaced the <br/<br> without addressing the .
I have corrected that to replace that string  as '.'  It then sees the end of sentence.  I took out the work.
I will attempt another submittal at the end of the day today!

**Comment by ramrao0102** [comment]
this umpteenth attempt might be a charm.  It is odd that when I see it on the forked repository on my end, the file looks nice and clean, and when I click on the - Add files via upload link here - , it looks garbled.

**Comment by cegme** [comment]
You can get the latest and go ahead and request a [fresh review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#re-requesting-a-review) when you are ready.

**Pull request closed without merging**
