### PR TITLE
Updated training, val, test

### PR DESCRIPTION
**Pull request by visionjoan**
pull pull pull

### CODE REVIEW

**Review by cegme — CHANGES_REQUESTED** [review]
Please pull the latest. Also, there may be few multi redaction examples

```
immediately attracted to the dashing film star ████████████████ (██████████████)
```

**Comment by cegme** [comment]
Go ahead and resolve the conflicts. You can press it and resolve it manually.
image

**Comment by visionjoan** [comment]
REsolved conflicts

**Review by cegme — CHANGES_REQUESTED** [review]
Please check the entries again. You have a t least on double redaction.

```
Bureau 17 has caught a Satanist from California, ████ (no relation to Dr. ██████)
```

**Comment by cegme** [comment]
Here is another one: 

```
She is immediately attracted to the dashing film star ████████████████ (██████████████)
```

**Comment by cegme** [comment]
When changes are complete re-request a review

**Comment by visionjoan** [comment]
Resolved multiple names, merged to recent

**Review by cegme — CHANGES_REQUESTED** [review]
Good changes. Makes sure you pull the latest code so I can integrate it.  Re request a review when ready

**Comment by visionjoan** [comment]
Hasn't my code been at the first queue?  I appreicate if you can merge mine first before adding others

**Review by visionjoan — COMMENTED** [review]
While line removed

**Comment by cegme** [comment]
@visionjoan you need to re-request a review there have been changes since your request

**Comment by cegme** [comment]
@visionjoan this is the queue best first to be available at the top https://github.com/cegme/cs5293sp22/pulls

**Review by cegme — APPROVED** [review]

**Pull request merged**
