### PR TITLE
Remove duplicate data and HTML br tags

### PR DESCRIPTION
**Pull request by siddhardha-maguluri**

### CODE REVIEW

**Review by cegme — CHANGES_REQUESTED** [review]
You removed or altered from entries and I cannot see why. Can you clarify this? Also some of the entries are not yours.

**Comment by siddhardha-maguluri** [comment]
1. I have removed 5 records of mine because those are mistakenly added by another user.
2. Regarding entries that are not mine showing as removed, I guess those changes are already merged.

**Comment by cegme** [comment]
> 1. I have removed 5 records of mine because those are mistakenly added by another user.
> 2. Regarding entries that are not mine showing as removed, I guess those changes are already merged.

I cannot verify this. Please try and update so I can merge

**Comment by siddhardha-maguluri** [comment]
Sure, I will raise a new pull request.

**Pull request closed without merging**
