### PR TITLE
Kaustubhpande73 patch 5

### PR DESCRIPTION
**Pull request by kaustubhpande73**
Removed the duplicates as mentioned by Nathan. Creating new pull request.

### CODE REVIEW

**Review by cegme — COMMENTED** [review]
Why are you removing these entries?

**Comment by cegme** [comment]
I cannot merge, please resolve conflicts

**Review by cegme — CHANGES_REQUESTED** [review]
Please clarify or correct the changes

**Comment by kaustubhpande73** [comment]
Nathan had mentioned I had duplicate entries. So, I replaced those entries and created a pull request

**Comment by cegme** [comment]
It looks like you are removing too many entries

image

**Comment by kaustubhpande73** [comment]
I replaced 20 entries. Should I add 10?

**Comment by cegme** [comment]
@kaustubhpande73 Make sure you have 90 in total. Remove conflicts and re-request a review so I can merge

**Comment by kaustubhpande73** [comment]
Dear Dr Grant, I am not able to resolve the conflicts. It seems disabled. I can't click on it

**Comment by cegme** [comment]
close the pr and submit a new one

**Pull request closed without merging**
